from lib.global_vars import *

#=======================================================#
#================== Global parameters ==================#
#=======================================================#
BUILD_LOG_LEVEL_DEFAULT = "INFO"
DOCKER_FILE_NAME_DEFAULT = "Dockerfile"
NOBUILD_FILE_NAME_DEFAULT = "NO_BUILD"
PARENT_VERSIONS_FILE_NAME_DEFAULT = "parent_versions"
PARAMETERS_FILE_NAME_DEFAULT = "parameters.yml"
JSONNET_BUILD_FUNCTION_DEFAULT = "build_docker"
JSONNET_DEPLOY_FUNCTION_DEFAULT = "deploy_docker"
CICD_STAGE_BUILD_LABEL_DEFAULT = "build-df"
GIT_MASTER_BRANCH_KEYWORDS_DEFAULT = [ "master", "main" ]
DOCKER_IMAGE_HUB_KEYWORD_DEFAULT = "official"
DOCKER_IMAGE_TAG_SEPARATOR_DEFAULT = "_"
DOCKER_IMAGES_PARENT_LEVELS_DEFAULT = 15
NO_BRANCH_DEFAULT = "nobranch"
PREPROD_KEY_DEFAULT = "preprod"
PROD_KEY_DEFAULT = "prod"
RECETTE_KEY_DEFAULT = "recette"
REPOSITORIES_WHITELIST_DEFAULT = []
ENABLE_DEPLOY_DEFAULT = False
DOCKER_BUILD_ARG_OPTION_DEFAULT = "--opt build-arg:"

BUILD_LOG_LEVEL = os.environ.get("BUILD_LOG_LEVEL", BUILD_LOG_LEVEL_DEFAULT).upper()
DOCKER_FILE_NAME = os.environ.get('DOCKER_FILE_NAME',DOCKER_FILE_NAME_DEFAULT)
NOBUILD_FILE_NAME = os.environ.get('NOBUILD_FILE_NAME',NOBUILD_FILE_NAME_DEFAULT)
PARENT_VERSIONS_FILE_NAME = os.environ.get('PARENT_VERSIONS_FILE_NAME',PARENT_VERSIONS_FILE_NAME_DEFAULT)
PARAMETERS_FILE_NAME = os.environ.get('PARAMETERS_FILE_NAME',PARAMETERS_FILE_NAME_DEFAULT)
JSONNET_BUILD_FUNCTION = os.environ.get('JSONNET_BUILD_FUNCTION',JSONNET_BUILD_FUNCTION_DEFAULT)
JSONNET_DEPLOY_FUNCTION = os.environ.get('JSONNET_DEPLOY_FUNCTION',JSONNET_DEPLOY_FUNCTION_DEFAULT)
CICD_STAGE_BUILD_LABEL = os.environ.get('CICD_STAGE_BUILD_LABEL',CICD_STAGE_BUILD_LABEL_DEFAULT)
GIT_MASTER_BRANCH_KEYWORDS = env.list("GIT_MASTER_BRANCH_KEYWORDS",GIT_MASTER_BRANCH_KEYWORDS_DEFAULT)
DOCKER_IMAGE_HUB_KEYWORD = os.environ.get('DOCKER_IMAGE_HUB_KEYWORD',DOCKER_IMAGE_HUB_KEYWORD_DEFAULT)
DOCKER_IMAGE_TAG_SEPARATOR = os.environ.get('DOCKER_IMAGE_TAG_SEPARATOR',DOCKER_IMAGE_TAG_SEPARATOR_DEFAULT)
DOCKER_IMAGES_PARENT_LEVELS = int(os.environ.get('DOCKER_IMAGES_PARENT_LEVELS',DOCKER_IMAGES_PARENT_LEVELS_DEFAULT))
NO_BRANCH = os.environ.get('NO_BRANCH',NO_BRANCH_DEFAULT)
PREPROD_KEY = os.environ.get('PREPROD_KEY',PREPROD_KEY_DEFAULT)
PROD_KEY = os.environ.get('PROD_KEY',PROD_KEY_DEFAULT)
RECETTE_KEY = os.environ.get('RECETTE_KEY',RECETTE_KEY_DEFAULT)
REPOSITORIES_WHITELIST = env.list("REPOSITORIES_WHITELIST",REPOSITORIES_WHITELIST_DEFAULT)
ENABLE_DEPLOY = env.bool("ENABLE_DEPLOY",ENABLE_DEPLOY_DEFAULT)
DOCKER_BUILD_ARG_OPTION = os.environ.get('DOCKER_BUILD_ARG_OPTION',DOCKER_BUILD_ARG_OPTION_DEFAULT)

logging.basicConfig(
    level=getattr(logging, BUILD_LOG_LEVEL),
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s"
)