from lib.global_vars import *

#=======================================================#
#================== Global parameters ==================#
#=======================================================#
DETECT_DEBT_LOG_LEVEL_DEFAULT = "INFO"

DETECT_INTERNAL_DEBT_ISSUE_TITLE_DEFAULT = "[Internal technical debt]"
DETECT_INTERNAL_DEBT_ISSUE_LABEL_DEFAULT = "En prod"
DETECT_INTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME_DEFAULT = ""
DETECT_INTERNAL_DEBT_ACTIVATE_ISSUE_DEFAULT = True

DETECT_INTERNAL_DEBT_ISSUE_TITLE = os.environ.get("DETECT_INTERNAL_DEBT_ISSUE_TITLE", DETECT_INTERNAL_DEBT_ISSUE_TITLE_DEFAULT)
DETECT_INTERNAL_DEBT_ISSUE_LABEL = os.environ.get("DETECT_INTERNAL_DEBT_ISSUE_LABEL", DETECT_INTERNAL_DEBT_ISSUE_LABEL_DEFAULT)
DETECT_INTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME = os.environ.get("DETECT_INTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME", DETECT_INTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME_DEFAULT)
DETECT_INTERNAL_DEBT_ACTIVATE_ISSUE = env.bool("DETECT_INTERNAL_DEBT_ACTIVATE_ISSUE", DETECT_INTERNAL_DEBT_ACTIVATE_ISSUE_DEFAULT)

DETECT_EXTERNAL_DEBT_ISSUE_TITLE_DEFAULT = "[External technical debt]"
DETECT_EXTERNAL_DEBT_ISSUE_LABEL_DEFAULT = "En prod"
DETECT_EXTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME_DEFAULT = ""
DETECT_EXTERNAL_DEBT_ACTIVATE_ISSUE_DEFAULT = True
DETECT_EXTERNAL_DEBT_ACTIVATE_DIRTY_COMPARAISON_DEFAULT = True

DETECT_EXTERNAL_DEBT_ISSUE_TITLE = os.environ.get("DETECT_EXTERNAL_DEBT_ISSUE_TITLE", DETECT_EXTERNAL_DEBT_ISSUE_TITLE_DEFAULT)
DETECT_EXTERNAL_DEBT_ISSUE_LABEL = os.environ.get("DETECT_EXTERNAL_DEBT_ISSUE_LABEL", DETECT_EXTERNAL_DEBT_ISSUE_LABEL_DEFAULT)
DETECT_EXTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME = os.environ.get("DETECT_EXTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME", DETECT_EXTERNAL_DEBT_ISSUE_ASSIGNEE_USERNAME_DEFAULT)
DETECT_EXTERNAL_DEBT_ACTIVATE_ISSUE = env.bool("DETECT_EXTERNAL_DEBT_ACTIVATE_ISSUE", DETECT_EXTERNAL_DEBT_ACTIVATE_ISSUE_DEFAULT)
DETECT_EXTERNAL_DEBT_ACTIVATE_DIRTY_COMPARAISON = env.bool("DETECT_EXTERNAL_DEBT_ACTIVATE_DIRTY_COMPARAISON", DETECT_EXTERNAL_DEBT_ACTIVATE_DIRTY_COMPARAISON_DEFAULT)

DETECT_DEBT_LOG_LEVEL = os.environ.get("DETECT_DEBT_LOG_LEVEL", DETECT_DEBT_LOG_LEVEL_DEFAULT).upper()

logging.basicConfig(
    level=getattr(logging, DETECT_DEBT_LOG_LEVEL),
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s"
)
