# coding=utf-8
import argparse
import requests
import os
import yaml
import json
from environs import Env

#=======================================================#
#============== Trigger Global parameters ==============#
#=======================================================#
env = Env()

#Default values
SETUP_GITLAB_TOKEN_NAME_DEFAULT = "CICD_JENKINS_TOKEN"
SETUP_TRIGGER_FOLDER_PATH_DEFAULT = "trigger-project/setup/"
SETUP_TRIGGER_FILE_ENDSWITH_DEFAULT = "triggers.yml"
SETUP_TRIGGER_CHANNEL_URL_DEFAULT = "https://tchap-bot.mel.e2.rie.gouv.fr/api/webhook/post/VaUQRGFvb5WhklqC6VYmXSlmLKXrcSTbRmoefdzkAbjvh4yXkOqMGZtSsgCsC50bjt0rSyBn1PqWByTirXOYmwhdJMTZfKxnBGUt"
SETUP_GITLAB_CI_CONFIG_PATH_DEFAULT = ".gitlab-ci.yml@snum/detn/gmcd/cicd/cicd-yaml"
SETUP_GITLAB_ACCOUNT_USERNAME_DEFAULT = "jenkins.inframel"
SETUP_TRIGGER_DESCRIPTION_DEFAULT = "Trigger cree par Jenkins"
SETUP_TRIGGER_ARGUMENTS_DEFAULT = {'all': 'trigger_files,branchs_only_trigger,branchs_mapping', 'gitlab': 'focus_trigger', 'jenkins': 'additional_params,token_name'}
SETUP_GITLAB_VARIABLE_TRIGGER_KEY_DEFAULT = "TRIGGER_TOKEN"
SETUP_JENKINS_TRIGGER_TOKEN_NAME_DEFAULT = "JENKINS_TRIGGER_TOKEN"
SETUP_VARIABLE_CONFIGURATION_KEY_DEFAULT = {'gitlab': 'GITLAB_TRIGGER_CONFIGURATION', 'jenkins': 'JENKINS_TRIGGER_CONFIGURATION'}

GITLAB_URL = os.environ.get('GITLAB_PROTOCOL',"https://") + os.environ.get('GITLAB_DOMAIN',"")
SETUP_GITLAB_TOKEN_NAME = os.environ.get('SETUP_GITLAB_TOKEN_NAME',SETUP_GITLAB_TOKEN_NAME_DEFAULT)
SETUP_TRIGGER_FOLDER_PATH = os.environ.get('SETUP_TRIGGER_FOLDER_PATH',SETUP_TRIGGER_FOLDER_PATH_DEFAULT)
SETUP_TRIGGER_FILE_ENDSWITH = os.environ.get('SETUP_TRIGGER_FILE_ENDSWITH',SETUP_TRIGGER_FILE_ENDSWITH_DEFAULT)
SETUP_TRIGGER_CHANNEL_URL = os.environ.get('SETUP_TRIGGER_CHANNEL_URL',SETUP_TRIGGER_CHANNEL_URL_DEFAULT)
SETUP_GITLAB_CI_CONFIG_PATH = os.environ.get('SETUP_GITLAB_CI_CONFIG_PATH',SETUP_GITLAB_CI_CONFIG_PATH_DEFAULT)
SETUP_GITLAB_ACCOUNT_USERNAME = os.environ.get('SETUP_GITLAB_ACCOUNT_USERNAME',SETUP_GITLAB_ACCOUNT_USERNAME_DEFAULT)
SETUP_TRIGGER_DESCRIPTION = os.environ.get('SETUP_TRIGGER_DESCRIPTION',SETUP_TRIGGER_DESCRIPTION_DEFAULT)
SETUP_TRIGGER_ARGUMENTS = env.json('SETUP_TRIGGER_ARGUMENTS',SETUP_TRIGGER_ARGUMENTS_DEFAULT)
SETUP_GITLAB_VARIABLE_TRIGGER_KEY = os.environ.get('SETUP_GITLAB_VARIABLE_TRIGGER_KEY',SETUP_GITLAB_VARIABLE_TRIGGER_KEY_DEFAULT)
SETUP_JENKINS_TRIGGER_TOKEN_NAME = os.environ.get('SETUP_JENKINS_TRIGGER_TOKEN_NAME',SETUP_JENKINS_TRIGGER_TOKEN_NAME_DEFAULT)
SETUP_CI_JOB_URL = os.environ.get('SETUP_CI_JOB_URL',"")
SETUP_VARIABLE_CONFIGURATION_KEY = os.environ.get('SETUP_VARIABLE_CONFIGURATION_KEY',SETUP_VARIABLE_CONFIGURATION_KEY_DEFAULT)

#=======================================================#
#=============== Build Global parameters ===============#
#=======================================================#
SETUP_BUILD_FOLDER_PATH_DEFAULT = "build-docker/setup/"
SETUP_BUILD_FILE_ENDSWITH_DEFAULT = "build.yml"
SETUP_BUILD_TOKEN_NAME_DEFAULT = "CICD_API_TOKEN"
SETUP_BUILD_TOKEN_SCOPE_DEFAULT = '["api","read_api","read_repository","write_repository","read_registry","write_registry"]'
SETUP_BUILD_TOKEN_ACCESS_LEVEL_DEFAULT = 40
SETUP_BUILD_ENABLE_BUILD_VARIABLE_NAME_DEFAULT = "ENABLE_BUILD"
SETUP_BUILD_DOCKERHUB_TOKEN_VARIABLE_NAME_DEFAULT = "DOCKERHUB_TOKEN"
SETUP_BUILD_DEPLOY_TOKEN_VARIABLE_NAME_DEFAULT = "DEPLOY_TOKEN"

SETUP_BUILD_FOLDER_PATH = os.environ.get('SETUP_BUILD_FOLDER_PATH',SETUP_BUILD_FOLDER_PATH_DEFAULT)
SETUP_BUILD_FILE_ENDSWITH = os.environ.get('SETUP_BUILD_FILE_ENDSWITH',SETUP_BUILD_FILE_ENDSWITH_DEFAULT)
SETUP_BUILD_TOKEN_NAME = os.environ.get('SETUP_BUILD_TOKEN_NAME',SETUP_BUILD_TOKEN_NAME_DEFAULT)
SETUP_BUILD_TOKEN_SCOPE = os.environ.get('SETUP_BUILD_TOKEN_SCOPE',SETUP_BUILD_TOKEN_SCOPE_DEFAULT)
SETUP_BUILD_TOKEN_ACCESS_LEVEL = os.environ.get('SETUP_BUILD_TOKEN_ACCESS_LEVEL',SETUP_BUILD_TOKEN_ACCESS_LEVEL_DEFAULT)
SETUP_BUILD_ENABLE_BUILD_VARIABLE_NAME = os.environ.get('SETUP_BUILD_ENABLE_BUILD_VARIABLE_NAME',SETUP_BUILD_ENABLE_BUILD_VARIABLE_NAME_DEFAULT)
SETUP_BUILD_DOCKERHUB_TOKEN_VARIABLE_NAME = os.environ.get('SETUP_BUILD_DOCKERHUB_TOKEN_VARIABLE_NAME',SETUP_BUILD_DOCKERHUB_TOKEN_VARIABLE_NAME_DEFAULT)
SETUP_BUILD_DEPLOY_TOKEN_VARIABLE_NAME = os.environ.get('SETUP_BUILD_DEPLOY_TOKEN_VARIABLE_NAME',SETUP_BUILD_DEPLOY_TOKEN_VARIABLE_NAME_DEFAULT)
SETUP_BUILD_DOCKERHUB_TOKEN = os.environ.get(SETUP_BUILD_DOCKERHUB_TOKEN_VARIABLE_NAME, '')
SETUP_BUILD_DEPLOY_TOKEN = os.environ.get(SETUP_BUILD_DEPLOY_TOKEN_VARIABLE_NAME, '')